# Generated by Django 3.0.3 on 2020-05-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_userid', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('country', models.CharField(max_length=255)),
                ('reciver_userid', models.CharField(max_length=255, unique=True)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=3)),
                ('loss', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('balance_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('country', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
            ],
        ),
    ]
