# Generated by Django 3.0.3 on 2020-05-02 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange_api', '0002_transaction_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date',
            field=models.CharField(blank=True, default='02/05/20 15:03:59', max_length=255),
        ),
    ]
