# Generated by Django 3.0.3 on 2020-05-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange_api', '0003_auto_20200502_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date',
            field=models.CharField(blank=True, default='02/05/20 15:07:32', max_length=255),
        ),
    ]
